/**
 * 
 */
package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import beans.amsBeans.PortDetailsBean;
import beans.amsBeans.VoyageBean;
import connectionfactory.DBConnectionFactory;
/**
 * @author Rohit
 * @date 2 march 2011
 */
public class VoyageDAO {
	private Connection con;
	private PreparedStatement stmt = null,stmt1=null;
	ResultSet rs=null;
	private static Log log = LogFactory.getLog("com.mobilefish.DemoAction");

	public VoyageDAO() {
		getConnection();
	}

	public void getConnection() {
		try {
			con = new DBConnectionFactory().getConnection();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		try {
			con.setAutoCommit(false);
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	public void closeAll(){
		try {
			if (stmt!=null){
				stmt.close();
			}
			if(con!=null){
				con.close();
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
/**
 * @author Rohit
 * @Date 2 march 2011
 * @Descripion This method is created for the Inserting the Voyage Details .
 * @method insert
 * @return result ;
 * @param objmVoyageBean,objmPortDetailsBean
**/
	public String insert(VoyageBean objmVoyageBean) {

			String result="";
			int autoIncrementId=0;
			try {
				
				stmt= con.prepareStatement("Insert into voyage " +
						"(login_scac, voyage_number, vessel_id, vessel_scac, crew_members," +
						" passengers, report_number, created_user, created_date)" +
						" VALUES (?,?,?,?,?,?,?,?,now()) ",Statement.RETURN_GENERATED_KEYS);
				stmt.setString(1,objmVoyageBean.getLoginScac());
				stmt.setString(2, objmVoyageBean.getVoyage());
				stmt.setInt(3,objmVoyageBean.getVesselId());
				stmt.setString(4,objmVoyageBean.getScacCode());
				stmt.setString(5, objmVoyageBean.getCrewMembers());
				stmt.setString(6, objmVoyageBean.getPassengers());
				stmt.setString(7, objmVoyageBean.getReportNumber());
				stmt.setString(8, objmVoyageBean.getCreatedUser());
				
				stmt.execute();
					rs = stmt.getGeneratedKeys();
				if (rs.next()) {
					System.out.println("rs go back" + rs.getString(1));
					autoIncrementId = rs.getInt(1);
				}
				else  
					System.out.println("Autogenerated key nt returned");
				stmt= con.prepareStatement("Insert into voyage_details " +
						"(login_scac, voyage_id, location_id, is_last_load_port, " +
						" terminal, sailing_date, arrival_date, is_load_port, " +
						" is_discharge_port, location_name)" +
						" values(?,?,?,?,?,?,?,?,?,?)");
				
				stmt.setString(1, objmVoyageBean.getLoginScac());
				stmt.setInt(2, autoIncrementId);
				for(int i=0;i<objmVoyageBean.getObjmPortDetailsBeans().size();i++){
					stmt.setInt(3, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLocationId());
					stmt.setBoolean(4, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLastLoadPort());
					stmt.setString(5, objmVoyageBean.getObjmPortDetailsBeans().get(i).getTerminal());
					stmt.setString(6, objmVoyageBean.getObjmPortDetailsBeans().get(i).getSailingDate());
					stmt.setString(7, objmVoyageBean.getObjmPortDetailsBeans().get(i).getArrivalDate());
					stmt.setBoolean(8, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLoad());
					stmt.setBoolean(9, objmVoyageBean.getObjmPortDetailsBeans().get(i).getDischarge());
					stmt.setString(10, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLocation());
					stmt.execute();
					
					stmt1= con.prepareStatement("update location " +
							"set is_voyage_created=true " +
							" where location_id=? and login_scac=?");
					
					stmt1.setInt(1, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLocationId());
					stmt1.setString(2, objmVoyageBean.getLoginScac());
					stmt1.executeUpdate();
				}

				stmt= con.prepareStatement("update vessel " +
						"set is_voyage_created=true " +
						" where vessel_id=? and login_scac=?");
				
				stmt.setInt(1, objmVoyageBean.getVesselId());
				stmt.setString(2, objmVoyageBean.getLoginScac());
				stmt.executeUpdate();
				
				result="Success";
			} catch (SQLException e) {
				e.printStackTrace();
				result="Exception";
			}catch (Exception e) {
				e.printStackTrace();
				result="Exception";
			}finally{
				try {
					if (!result.equals("Success")) {
						con.rollback();
						log.error("Error in Insert query...");
						result="Fail";
					}
					else 
						con.commit();
			
				} catch (Exception e2) {
					e2.printStackTrace();
				}
			}
			return result;
		}
	
	/**
	 * @author Rohit
	 * @Date 28 feb 2011
	 * @Descripion This method is for the Update Voyage Details.
	 * @method Update
	 * @return result;
	 * @param objmVoyageBean,objmPortDetailsBean
	**/
		public String update (VoyageBean objmVoyageBean) {

			String result="";
			int a =0,b=0,c=0;
			try {
				stmt = con.prepareStatement("update voyage set crew_members=?, " +
						" passengers =?, report_number =? where voyage_id=?");
				stmt.setString(1,objmVoyageBean.getCrewMembers());
				stmt.setString(2,objmVoyageBean.getPassengers());
				stmt.setString(3,objmVoyageBean.getReportNumber());
				stmt.setInt(4, objmVoyageBean.getVoyageId());
				
				a=stmt.executeUpdate();
				stmt = con.prepareStatement("delete from voyage_details where voyage_id=?");
				stmt.setInt(1, objmVoyageBean.getVoyageId());
				b=stmt.executeUpdate();
				
				stmt= con.prepareStatement("Insert into voyage_details " +
						"(login_scac, voyage_id, location_id, is_last_load_port, " +
						" terminal, sailing_date, arrival_date, is_load_port, " +
						" is_discharge_port, location_name)" +
						" values(?,?,?,?,?,?,?,?,?,?)");
				
				stmt.setString(1, objmVoyageBean.getLoginScac());
				stmt.setInt(2, objmVoyageBean.getVoyageId());
				for(int i=0;i<objmVoyageBean.getObjmPortDetailsBeans().size();i++){
					stmt.setInt(3, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLocationId());
					stmt.setBoolean(4, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLastLoadPort());
					stmt.setString(5, objmVoyageBean.getObjmPortDetailsBeans().get(i).getTerminal());
					stmt.setString(6, objmVoyageBean.getObjmPortDetailsBeans().get(i).getSailingDate());
					stmt.setString(7, objmVoyageBean.getObjmPortDetailsBeans().get(i).getArrivalDate());
					stmt.setBoolean(8, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLoad());
					stmt.setBoolean(9, objmVoyageBean.getObjmPortDetailsBeans().get(i).getDischarge());
					stmt.setString(10, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLocation());
					c=stmt.executeUpdate();
					
					stmt1= con.prepareStatement("update location " +
							"set is_voyage_created=true " +
							" where location_id=? and login_scac=?");
					
					stmt1.setInt(1, objmVoyageBean.getObjmPortDetailsBeans().get(i).getLocationId());
					stmt1.setString(2, objmVoyageBean.getLoginScac());
					stmt1.executeUpdate();
				}
				if(a>0 && b>0 && c>0){
					result="Success";
				}else{
					result="Fail";
				}
			} catch (SQLException e) {
				e.printStackTrace();
				result="Exception";
			}catch (Exception e) {
				e.printStackTrace();
				result="Exception";
			}finally{
				try {
					if (result.equals("Success"))
						con.commit();
					else{
						con.rollback();
						log.error("Error in Update query...");
						result="Fail";
					}	
				} catch (Exception e2) {
					e2.printStackTrace();
				}
			}
			return result;
		}
/**
 * @author Rohit 
 * @Date 2 march 2011
 * @Descripion This method is for the delete Voyage Details.
 * @method delete
 * @return result;
 * @param voyageId
**/
		public String delete (int voyageId ) {
			String result="";
			int a=0,b=0;
			try {
				stmt = con.prepareStatement("Delete from voyage where voyage_id=?");
				stmt.setInt(1, voyageId);
				a=stmt.executeUpdate();
				
				stmt = con.prepareStatement("Delete from voyage_details where voyage_id=?");
				stmt.setInt(1, voyageId);
				
				b= stmt.executeUpdate();
				if(a>0 && b>0){
				result="Success";
				}else {
					result="Fail";
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}finally{
				try {
					if (result.equals("Success"))
						con.commit();
					else{
						con.rollback();
						log.error("Error in Delete query...");
						result="Fail";
					}	
				} catch (Exception e2) {
					e2.printStackTrace();
				}
			}
			return result;
		}	
		
/**
 * @author Rohit
 * @Date 2 March 2011
 * @Descripion This method is for reriving the list of Voyage Details.
 * @method getList
 * @return objmList;
 *  @param searchVoyage,loginScac
**/
		public ArrayList<VoyageBean> getList (String searchVoyage ,String loginScac ) {
			ArrayList<VoyageBean> objmList=null;
			ResultSet rs=null;
			try {
				objmList = new ArrayList<VoyageBean>();
				
				VoyageBean objmVoyageBean;
				stmt = con.prepareStatement("Select v.voyage_id, v.voyage_number, " +
						" v.vessel_id,ve.vessel_name from voyage v,vessel ve  where v.vessel_id=ve.vessel_id and v.login_scac=? and v.voyage_number like ?");
				stmt.setString(1,loginScac);
				stmt.setString(2, searchVoyage+"%");
				rs= stmt.executeQuery();
				while(rs.next()){
					objmVoyageBean = new VoyageBean(); 
					objmVoyageBean.setVoyageId(rs.getInt(1));
					objmVoyageBean.setVoyage(rs.getString(2));
					objmVoyageBean.setVesselId(rs.getInt(3));
					objmVoyageBean.setVesselName(rs.getString(4));
					objmList.add(objmVoyageBean);
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
			return objmList;
		}

/**
 * @author Ajoy
 * @Date 20 April 2011
 * @Descripion This method is for reriving the list of Voyage Details.
 * @method getList
 * @return objmList;
 *  @param vesselId,loginScac
**/
				public ArrayList<VoyageBean> getList (int vesselId ,String loginScac ) {
					ArrayList<VoyageBean> objmList=null;
					ResultSet rs=null;
					try {
						objmList = new ArrayList<VoyageBean>();
						
						VoyageBean objmVoyageBean;
						stmt = con.prepareStatement("Select v.voyage_id, v.voyage_number, " +
								" v.vessel_id,ve.vessel_name from voyage v,vessel ve where v.vessel_id = ve.vessel_id and v.login_scac=? and v.vessel_id = ?");
						stmt.setString(1,loginScac);
						stmt.setInt(2, vesselId);
						rs= stmt.executeQuery();
						while(rs.next()){
							objmVoyageBean = new VoyageBean(); 
							objmVoyageBean.setVoyageId(rs.getInt(1));
							objmVoyageBean.setVoyage(rs.getString(2));
							objmVoyageBean.setVesselId(rs.getInt(3));
							objmVoyageBean.setVesselName(rs.getString(4));
							objmList.add(objmVoyageBean);
						}
					} catch (SQLException e) {
						e.printStackTrace();
					}
					return objmList;
				}		
/**
 * @author Rohit 
 * @Date 1 march 2011
 * @Descripion This method is for the retriving the Vessel Details .
 * @method getData
 * @return objmVesselBean;
 * @param vesselId
**/
		public VoyageBean getData (int voyageId ) {
			ResultSet rs=null;
			VoyageBean objmVoyageBean=null;
			ArrayList<PortDetailsBean>objmList=null;
			PortDetailsBean objmPortDetailsBean;
			try {
				objmList = new ArrayList<PortDetailsBean>();
				objmVoyageBean = new VoyageBean();
				stmt = con.prepareStatement("Select voyage_id, voyage_number, a.vessel_id ,b.vessel_name," +
						" vessel_scac, crew_members, passengers, report_number from voyage a, " +
						" vessel b " +
						" where a.voyage_id= ?" + 
						" and b.vessel_id = a.vessel_id");
				stmt.setInt(1, voyageId);
				rs= stmt.executeQuery();
				while(rs.next()){
					objmVoyageBean.setVoyageId(rs.getInt(1));
					objmVoyageBean.setVoyage(rs.getString(2));
					objmVoyageBean.setVesselId(rs.getInt(3));
					objmVoyageBean.setVesselName(rs.getString(4));
					objmVoyageBean.setScacCode(rs.getString(5));
					objmVoyageBean.setCrewMembers(rs.getString(6));
					objmVoyageBean.setPassengers(rs.getString(7));
					objmVoyageBean.setReportNumber(rs.getString(8));
				}
				stmt = con.prepareStatement("select l.location_name,v.location_id," +
						" v.terminal,DATE(v.arrival_date),DATE(v.sailing_date),v.is_load_port," +
						" v.is_discharge_port,is_last_load_port, ifnull((select distinct 1 " +
						" from voyage_port_details v1 where v1.login_scac = v.login_scac " +
						" and v1.voyage_id = v.voyage_id and (v1.load_port = l.location_code " +
						" or v1.discharge_port = l.location_code)),0) as is_bill_created " +
						" from  location l, voyage_details v where v.voyage_id = ? " +
						" and l.location_id = v.location_id order by v.sailing_date");
				stmt.setInt(1, voyageId);
				rs= stmt.executeQuery();
				while(rs.next()){
					objmPortDetailsBean = new PortDetailsBean();
					objmPortDetailsBean.setLocation(rs.getString(1));
					objmPortDetailsBean.setLocationId(rs.getInt(2));
					objmPortDetailsBean.setTerminal(rs.getString(3));
					objmPortDetailsBean.setArrivalDate(rs.getString(4));
					objmPortDetailsBean.setSailingDate(rs.getString(5));
					objmPortDetailsBean.setLoad(rs.getBoolean(6));
					objmPortDetailsBean.setDischarge(rs.getBoolean(7));
					objmPortDetailsBean.setLastLoadPort(rs.getBoolean(8));
					objmPortDetailsBean.setIsAmsSent(rs.getBoolean(9));
					objmList.add(objmPortDetailsBean);
				}
				objmVoyageBean.setObjmPortDetailsBeans(objmList);
				
			} catch (SQLException e) {
				e.printStackTrace();
			}
			return objmVoyageBean;
		}
		
/**
 * @author Rohit
 * @date 2 March 2011
 * @method isExist
 * @return result
 * @parm vesselName,loginScac, voyageNumber
**/
	public Boolean isExist(String loginScac, int vesselId , String voyageNumber){
		ResultSet rs=null;
		Boolean result=true;
		try{
			stmt = con.prepareStatement("Select " +
					" voyage_id, login_scac, voyage_number, vessel_id, vessel_scac," +
					" crew_members, passengers, report_number, created_user, created_date" +
					" from voyage " +
					" where login_scac=? and vessel_id=? and voyage_number=?");
			stmt.setString(1, loginScac);		
			stmt.setInt(2, vesselId);
			stmt.setString(3, voyageNumber);
					rs=stmt.executeQuery();
			if (rs.next()){
				result=true;
			}else{
				result=false;
			}
		}catch(Exception e){
			e.printStackTrace();
		}
		return result;
	}
	
	public int getVoyageId(String loginScac, int vesselId , String voyageNumber){
		ResultSet rs=null;
		try{
			stmt = con.prepareStatement("Select " +
					" voyage_id from voyage " +
					" where login_scac=? and vessel_id=? and voyage_number=?");
			stmt.setString(1, loginScac);		
			stmt.setInt(2, vesselId);
			stmt.setString(3, voyageNumber);
					rs=stmt.executeQuery();
			if (rs.next()){
				return rs.getInt(1);
			}
		}catch(Exception e){
			e.printStackTrace();
		}
		return 0;
	}
	public Object getVoyage(String loginScac, String vesselId) {
		ArrayList<VoyageBean> objmList=null;
		ResultSet rs=null;
		try {
			objmList = new ArrayList<VoyageBean>();
			
			VoyageBean objmVoyageBean;
			stmt = con.prepareStatement("Select voyage_id, voyage_number " +
					" FROM voyage " +
					" where vessel_id = ? and  login_scac=? ");				
			stmt.setString(1,vesselId);
			stmt.setString(2,loginScac);
			System.out.println(stmt.toString());
			rs= stmt.executeQuery();				
			while(rs.next()){
				objmVoyageBean =new VoyageBean();
				objmVoyageBean.setVoyageId(rs.getInt(1));
				objmVoyageBean.setVoyage(rs.getString(2));					
				objmList.add(objmVoyageBean);
			}				
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return objmList;
	}
	
	public Object getVoyageList(String loginScac, String vesselId) {
		ArrayList<VoyageBean> objmList=null;
		ResultSet rs=null;
		try {
			objmList = new ArrayList<VoyageBean>();
			
			VoyageBean objmVoyageBean;
			stmt = con.prepareStatement("Select distinct a.voyage_id, a.voyage_number" +
					" FROM voyage a, bill_header b" +
					" where a.vessel_id = ?" +
					" and  a.login_scac= ?" +
					" and b.voyage_id = a.voyage_id" +
					" and b.login_scac = a.login_scac");				
			stmt.setString(1,vesselId);
			stmt.setString(2,loginScac);
			log.info(stmt.toString());
			rs= stmt.executeQuery();				
			while(rs.next()){
				objmVoyageBean =new VoyageBean();
				objmVoyageBean.setVoyageId(rs.getInt(1));
				objmVoyageBean.setVoyage(rs.getString(2));					
				objmList.add(objmVoyageBean);
			}				
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return objmList;
	}
	
	public int getVesselId(String vesselName, String loginScac) {
		try {
			stmt = con.prepareStatement("Select vessel_id from vessel " +
					" where vessel_name=? and login_scac=?");
			stmt.setString(1, vesselName);
			stmt.setString(2, loginScac);
			rs=stmt.executeQuery();
			log.info(stmt.toString());
			rs=stmt.executeQuery();
			if (rs.next()){
				return rs.getInt(1);
			}
		} catch (SQLException e) {			
			e.printStackTrace();
		}
		return 0;
	}
}
